Update blank.yml

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -12,8 +12,25 @@ jobs:
     runs-on: windows-latest
     steps:
       - uses: actions/checkout@v4
+
+      - name: Install ClamAV
+        run: |
+          choco install clamav --force
+          freshclam
+        shell: powershell
+
+      - name: Scan ZIP and EXE for viruses
+        run: |
+          clamscan --infected --recursive --no-summary ./HiloPlugin.zip ./HiloPlugin.exe
+          if ($LASTEXITCODE -ne 0) {
+            Write-Error "Virus detected! Aborting release."
+            exit 1
+          }
+        shell: powershell
+
       - name: Update Release
         uses: softprops/action-gh-release@v2
+        if: success() # Chỉ chạy nếu scan pass
         with:
           tag_name: ${{ github.ref_name == 'PublishHttps' && 'https-latest' || github.ref_name == 'PublishHttp' && 'http-latest' || 'all-latest' }}
           files: |
@@ -23,6 +40,6 @@ jobs:
           body: Auto-updated release for ${{ github.ref_name }}
           target_commitish: ${{ github.sha }}
           prerelease: false
-          generate_release_notes: false  # Ngăn tạo release notes và source code archives
+          generate_release_notes: false
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
